### ISSUE TITLE
No email contact - Sirius in tournament

### ISSUE THREAD

**Issue by GrahamCCRL** [mcthouacbb/Sirius#25]
104TH AMATEUR SERIES (Division 7)

Seawall 20231015 64-bit
Weiawaga 5.0 64-bit
Leorik 2.5 64-bit
Sirius 5.0 64-bit (new)
4ku 3.1 64-bit
Ceibo 0.9 64-bit
Coiled 1.2 NoNNUE 64-bit
Shallow 5.0 64-bit (promoted)
Inanis 1.2.0 64-bit (promoted)
Odonata 0.7.0 64-bit (promoted)
Mess 0.3.0 64-bit (promoted)
Colossus 2022a 64-bit (promoted)
Fridolin 4.0 64-bit (promoted)
Nawito 22.07 64-bit (promoted)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

**Comment by mcthouacbb** [comment]
My email is mcthouacbb@gmail.com(though I don't read my email often)
You can also contact me as A_randomnoob on discord(I'm in the engine programming and stockfish server)

**Comment by GrahamCCRL** [comment]
Thanks. Much appreciated. :-)
