### ISSUE TITLE
Author name?

### ISSUE THREAD

**Issue by rwbc** [mcthouacbb/Sirius#89]
Hi,

Just in case you want Sirius to be added to the XB/UCI chronology, may I ask if you want to remain anonymous?
(anonymous entries are not possible there)

https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM
(running since 2002)

Guenther (RWBC)

**Comment by mcthouacbb** [comment]
Sorry for the late reply. yes, I would prefer to remain anonymous
